name: sixside
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  firebase_auth: ^6.7.0
  firebase_core: ^4.15.0
  firebase_ui_auth: ^3.1.1
  flutter:
    sdk: flutter
  hexagon: ^0.2.0
  http: ^1.6.0
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.31.1
  mockito: ^5.8.1
  build_runner: ^2.16.1

flutter:
  uses-material-design: true
